services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8080:8080"

  cli:
    build:
      context: .
      dockerfile: cmd/cli/Dockerfile
    depends_on:
      - api
    stdin_open: true
    tty: true