/*
go-quiz

Testing QuizzesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_QuizzesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test QuizzesAPIService QuizzesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.QuizzesAPI.QuizzesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QuizzesAPIService QuizzesQuizIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var quizId int32

		resp, httpRes, err := apiClient.QuizzesAPI.QuizzesQuizIdGet(context.Background(), quizId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QuizzesAPIService QuizzesQuizIdResultsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var quizId int32

		resp, httpRes, err := apiClient.QuizzesAPI.QuizzesQuizIdResultsGet(context.Background(), quizId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test QuizzesAPIService QuizzesQuizIdSubmitPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var quizId int32

		resp, httpRes, err := apiClient.QuizzesAPI.QuizzesQuizIdSubmitPost(context.Background(), quizId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
