/*
go-quiz

This is the API documentation for go-quiz, a simple Quiz API allowing users to obtain quizzes, answer the questions and see their results compared to other users.

API version: 1.0
Contact: dtslubbersen@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiTokenCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTokenCreatedResponse{}

// ApiTokenCreatedResponse struct for ApiTokenCreatedResponse
type ApiTokenCreatedResponse struct {
	ExpiresIn *int32           `json:"expires_in,omitempty"`
	Token     *string          `json:"token,omitempty"`
	User      *ApiUserResponse `json:"user,omitempty"`
}

// NewApiTokenCreatedResponse instantiates a new ApiTokenCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTokenCreatedResponse() *ApiTokenCreatedResponse {
	this := ApiTokenCreatedResponse{}
	return &this
}

// NewApiTokenCreatedResponseWithDefaults instantiates a new ApiTokenCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTokenCreatedResponseWithDefaults() *ApiTokenCreatedResponse {
	this := ApiTokenCreatedResponse{}
	return &this
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *ApiTokenCreatedResponse) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTokenCreatedResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *ApiTokenCreatedResponse) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given int32 and assigns it to the ExpiresIn field.
func (o *ApiTokenCreatedResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *ApiTokenCreatedResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTokenCreatedResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *ApiTokenCreatedResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *ApiTokenCreatedResponse) SetToken(v string) {
	o.Token = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ApiTokenCreatedResponse) GetUser() ApiUserResponse {
	if o == nil || IsNil(o.User) {
		var ret ApiUserResponse
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiTokenCreatedResponse) GetUserOk() (*ApiUserResponse, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ApiTokenCreatedResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given ApiUserResponse and assigns it to the User field.
func (o *ApiTokenCreatedResponse) SetUser(v ApiUserResponse) {
	o.User = &v
}

func (o ApiTokenCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTokenCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

type NullableApiTokenCreatedResponse struct {
	value *ApiTokenCreatedResponse
	isSet bool
}

func (v NullableApiTokenCreatedResponse) Get() *ApiTokenCreatedResponse {
	return v.value
}

func (v *NullableApiTokenCreatedResponse) Set(val *ApiTokenCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTokenCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTokenCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTokenCreatedResponse(val *ApiTokenCreatedResponse) *NullableApiTokenCreatedResponse {
	return &NullableApiTokenCreatedResponse{value: val, isSet: true}
}

func (v NullableApiTokenCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTokenCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
