/*
go-quiz

This is the API documentation for go-quiz, a simple Quiz API allowing users to obtain quizzes, answer the questions and see their results compared to other users.

API version: 1.0
Contact: dtslubbersen@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiSubmitQuizAnswersPayloadAnswersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSubmitQuizAnswersPayloadAnswersInner{}

// ApiSubmitQuizAnswersPayloadAnswersInner struct for ApiSubmitQuizAnswersPayloadAnswersInner
type ApiSubmitQuizAnswersPayloadAnswersInner struct {
	AnswerIndex int32 `json:"answer_index"`
	QuestionId int32 `json:"question_id"`
}

type _ApiSubmitQuizAnswersPayloadAnswersInner ApiSubmitQuizAnswersPayloadAnswersInner

// NewApiSubmitQuizAnswersPayloadAnswersInner instantiates a new ApiSubmitQuizAnswersPayloadAnswersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSubmitQuizAnswersPayloadAnswersInner(answerIndex int32, questionId int32) *ApiSubmitQuizAnswersPayloadAnswersInner {
	this := ApiSubmitQuizAnswersPayloadAnswersInner{}
	this.AnswerIndex = answerIndex
	this.QuestionId = questionId
	return &this
}

// NewApiSubmitQuizAnswersPayloadAnswersInnerWithDefaults instantiates a new ApiSubmitQuizAnswersPayloadAnswersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSubmitQuizAnswersPayloadAnswersInnerWithDefaults() *ApiSubmitQuizAnswersPayloadAnswersInner {
	this := ApiSubmitQuizAnswersPayloadAnswersInner{}
	return &this
}

// GetAnswerIndex returns the AnswerIndex field value
func (o *ApiSubmitQuizAnswersPayloadAnswersInner) GetAnswerIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AnswerIndex
}

// GetAnswerIndexOk returns a tuple with the AnswerIndex field value
// and a boolean to check if the value has been set.
func (o *ApiSubmitQuizAnswersPayloadAnswersInner) GetAnswerIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AnswerIndex, true
}

// SetAnswerIndex sets field value
func (o *ApiSubmitQuizAnswersPayloadAnswersInner) SetAnswerIndex(v int32) {
	o.AnswerIndex = v
}

// GetQuestionId returns the QuestionId field value
func (o *ApiSubmitQuizAnswersPayloadAnswersInner) GetQuestionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuestionId
}

// GetQuestionIdOk returns a tuple with the QuestionId field value
// and a boolean to check if the value has been set.
func (o *ApiSubmitQuizAnswersPayloadAnswersInner) GetQuestionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestionId, true
}

// SetQuestionId sets field value
func (o *ApiSubmitQuizAnswersPayloadAnswersInner) SetQuestionId(v int32) {
	o.QuestionId = v
}

func (o ApiSubmitQuizAnswersPayloadAnswersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSubmitQuizAnswersPayloadAnswersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer_index"] = o.AnswerIndex
	toSerialize["question_id"] = o.QuestionId
	return toSerialize, nil
}

func (o *ApiSubmitQuizAnswersPayloadAnswersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer_index",
		"question_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiSubmitQuizAnswersPayloadAnswersInner := _ApiSubmitQuizAnswersPayloadAnswersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiSubmitQuizAnswersPayloadAnswersInner)

	if err != nil {
		return err
	}

	*o = ApiSubmitQuizAnswersPayloadAnswersInner(varApiSubmitQuizAnswersPayloadAnswersInner)

	return err
}

type NullableApiSubmitQuizAnswersPayloadAnswersInner struct {
	value *ApiSubmitQuizAnswersPayloadAnswersInner
	isSet bool
}

func (v NullableApiSubmitQuizAnswersPayloadAnswersInner) Get() *ApiSubmitQuizAnswersPayloadAnswersInner {
	return v.value
}

func (v *NullableApiSubmitQuizAnswersPayloadAnswersInner) Set(val *ApiSubmitQuizAnswersPayloadAnswersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSubmitQuizAnswersPayloadAnswersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSubmitQuizAnswersPayloadAnswersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSubmitQuizAnswersPayloadAnswersInner(val *ApiSubmitQuizAnswersPayloadAnswersInner) *NullableApiSubmitQuizAnswersPayloadAnswersInner {
	return &NullableApiSubmitQuizAnswersPayloadAnswersInner{value: val, isSet: true}
}

func (v NullableApiSubmitQuizAnswersPayloadAnswersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSubmitQuizAnswersPayloadAnswersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


