/*
go-quiz

This is the API documentation for go-quiz, a simple Quiz API allowing users to obtain quizzes, answer the questions and see their results compared to other users.

API version: 1.0
Contact: dtslubbersen@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QuizzesQuizIdSubmitPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuizzesQuizIdSubmitPostRequest{}

// QuizzesQuizIdSubmitPostRequest struct for QuizzesQuizIdSubmitPostRequest
type QuizzesQuizIdSubmitPostRequest struct {
	Answers []ApiQuestionAnswerPayload `json:"answers"`
}

type _QuizzesQuizIdSubmitPostRequest QuizzesQuizIdSubmitPostRequest

// NewQuizzesQuizIdSubmitPostRequest instantiates a new QuizzesQuizIdSubmitPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuizzesQuizIdSubmitPostRequest(answers []ApiQuestionAnswerPayload) *QuizzesQuizIdSubmitPostRequest {
	this := QuizzesQuizIdSubmitPostRequest{}
	this.Answers = answers
	return &this
}

// NewQuizzesQuizIdSubmitPostRequestWithDefaults instantiates a new QuizzesQuizIdSubmitPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuizzesQuizIdSubmitPostRequestWithDefaults() *QuizzesQuizIdSubmitPostRequest {
	this := QuizzesQuizIdSubmitPostRequest{}
	return &this
}

// GetAnswers returns the Answers field value
func (o *QuizzesQuizIdSubmitPostRequest) GetAnswers() []ApiQuestionAnswerPayload {
	if o == nil {
		var ret []ApiQuestionAnswerPayload
		return ret
	}

	return o.Answers
}

// GetAnswersOk returns a tuple with the Answers field value
// and a boolean to check if the value has been set.
func (o *QuizzesQuizIdSubmitPostRequest) GetAnswersOk() ([]ApiQuestionAnswerPayload, bool) {
	if o == nil {
		return nil, false
	}
	return o.Answers, true
}

// SetAnswers sets field value
func (o *QuizzesQuizIdSubmitPostRequest) SetAnswers(v []ApiQuestionAnswerPayload) {
	o.Answers = v
}

func (o QuizzesQuizIdSubmitPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuizzesQuizIdSubmitPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answers"] = o.Answers
	return toSerialize, nil
}

func (o *QuizzesQuizIdSubmitPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuizzesQuizIdSubmitPostRequest := _QuizzesQuizIdSubmitPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuizzesQuizIdSubmitPostRequest)

	if err != nil {
		return err
	}

	*o = QuizzesQuizIdSubmitPostRequest(varQuizzesQuizIdSubmitPostRequest)

	return err
}

type NullableQuizzesQuizIdSubmitPostRequest struct {
	value *QuizzesQuizIdSubmitPostRequest
	isSet bool
}

func (v NullableQuizzesQuizIdSubmitPostRequest) Get() *QuizzesQuizIdSubmitPostRequest {
	return v.value
}

func (v *NullableQuizzesQuizIdSubmitPostRequest) Set(val *QuizzesQuizIdSubmitPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuizzesQuizIdSubmitPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuizzesQuizIdSubmitPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuizzesQuizIdSubmitPostRequest(val *QuizzesQuizIdSubmitPostRequest) *NullableQuizzesQuizIdSubmitPostRequest {
	return &NullableQuizzesQuizIdSubmitPostRequest{value: val, isSet: true}
}

func (v NullableQuizzesQuizIdSubmitPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuizzesQuizIdSubmitPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
