/*
go-quiz

This is the API documentation for go-quiz, a simple Quiz API allowing users to obtain quizzes, answer the questions and see their results compared to other users.

API version: 1.0
Contact: dtslubbersen@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiQuestionAnswerPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiQuestionAnswerPayload{}

// ApiQuestionAnswerPayload struct for ApiQuestionAnswerPayload
type ApiQuestionAnswerPayload struct {
	AnswerIndex int32 `json:"answer_index"`
	QuestionId  int32 `json:"question_id"`
}

type _ApiQuestionAnswerPayload ApiQuestionAnswerPayload

// NewApiQuestionAnswerPayload instantiates a new ApiQuestionAnswerPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiQuestionAnswerPayload(answerIndex int32, questionId int32) *ApiQuestionAnswerPayload {
	this := ApiQuestionAnswerPayload{}
	this.AnswerIndex = answerIndex
	this.QuestionId = questionId
	return &this
}

// NewApiQuestionAnswerPayloadWithDefaults instantiates a new ApiQuestionAnswerPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiQuestionAnswerPayloadWithDefaults() *ApiQuestionAnswerPayload {
	this := ApiQuestionAnswerPayload{}
	return &this
}

// GetAnswerIndex returns the AnswerIndex field value
func (o *ApiQuestionAnswerPayload) GetAnswerIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AnswerIndex
}

// GetAnswerIndexOk returns a tuple with the AnswerIndex field value
// and a boolean to check if the value has been set.
func (o *ApiQuestionAnswerPayload) GetAnswerIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AnswerIndex, true
}

// SetAnswerIndex sets field value
func (o *ApiQuestionAnswerPayload) SetAnswerIndex(v int32) {
	o.AnswerIndex = v
}

// GetQuestionId returns the QuestionId field value
func (o *ApiQuestionAnswerPayload) GetQuestionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QuestionId
}

// GetQuestionIdOk returns a tuple with the QuestionId field value
// and a boolean to check if the value has been set.
func (o *ApiQuestionAnswerPayload) GetQuestionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestionId, true
}

// SetQuestionId sets field value
func (o *ApiQuestionAnswerPayload) SetQuestionId(v int32) {
	o.QuestionId = v
}

func (o ApiQuestionAnswerPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiQuestionAnswerPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer_index"] = o.AnswerIndex
	toSerialize["question_id"] = o.QuestionId
	return toSerialize, nil
}

func (o *ApiQuestionAnswerPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer_index",
		"question_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiQuestionAnswerPayload := _ApiQuestionAnswerPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiQuestionAnswerPayload)

	if err != nil {
		return err
	}

	*o = ApiQuestionAnswerPayload(varApiQuestionAnswerPayload)

	return err
}

type NullableApiQuestionAnswerPayload struct {
	value *ApiQuestionAnswerPayload
	isSet bool
}

func (v NullableApiQuestionAnswerPayload) Get() *ApiQuestionAnswerPayload {
	return v.value
}

func (v *NullableApiQuestionAnswerPayload) Set(val *ApiQuestionAnswerPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableApiQuestionAnswerPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableApiQuestionAnswerPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiQuestionAnswerPayload(val *ApiQuestionAnswerPayload) *NullableApiQuestionAnswerPayload {
	return &NullableApiQuestionAnswerPayload{value: val, isSet: true}
}

func (v NullableApiQuestionAnswerPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiQuestionAnswerPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
