/*
go-quiz

This is the API documentation for go-quiz, a simple Quiz API allowing users to obtain quizzes, answer the questions and see their results compared to other users.

API version: 1.0
Contact: dtslubbersen@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QuizzesGet400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuizzesGet400Response{}

// QuizzesGet400Response struct for QuizzesGet400Response
type QuizzesGet400Response struct {
	Data       map[string]interface{} `json:"data,omitempty"`
	Error      *string                `json:"error,omitempty"`
	StatusCode *int32                 `json:"status_code,omitempty"`
}

// NewQuizzesGet400Response instantiates a new QuizzesGet400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuizzesGet400Response() *QuizzesGet400Response {
	this := QuizzesGet400Response{}
	return &this
}

// NewQuizzesGet400ResponseWithDefaults instantiates a new QuizzesGet400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuizzesGet400ResponseWithDefaults() *QuizzesGet400Response {
	this := QuizzesGet400Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *QuizzesGet400Response) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuizzesGet400Response) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *QuizzesGet400Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *QuizzesGet400Response) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *QuizzesGet400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuizzesGet400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *QuizzesGet400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *QuizzesGet400Response) SetError(v string) {
	o.Error = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *QuizzesGet400Response) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuizzesGet400Response) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *QuizzesGet400Response) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *QuizzesGet400Response) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o QuizzesGet400Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuizzesGet400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableQuizzesGet400Response struct {
	value *QuizzesGet400Response
	isSet bool
}

func (v NullableQuizzesGet400Response) Get() *QuizzesGet400Response {
	return v.value
}

func (v *NullableQuizzesGet400Response) Set(val *QuizzesGet400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQuizzesGet400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQuizzesGet400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuizzesGet400Response(val *QuizzesGet400Response) *NullableQuizzesGet400Response {
	return &NullableQuizzesGet400Response{value: val, isSet: true}
}

func (v NullableQuizzesGet400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuizzesGet400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
